substitutions:
  _REGION: asia-northeast1
  _SERVICE: horse-demo
  _AR_REPO: demo-repo
  _IMAGE_NAME: horse
  _APP_DIR: app

steps:
  - name: gcr.io/cloud-builders/docker
    id: build
    dir: ${_APP_DIR}
    args:
      - build
      - -t
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:$SHORT_SHA'
      - -t
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:latest'
      - .

  - name: gcr.io/cloud-builders/docker
    id: push-sha
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:$SHORT_SHA']

  - name: gcr.io/cloud-builders/docker
    id: push-latest
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:latest']

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
  id: notify
  entrypoint: bash
  args:
    - -c
    - |
      gcloud pubsub topics publish image-updated \
        --message="deploy" \
        --attribute="image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:$SHORT_SHA"

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:$SHORT_SHA'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:latest'
# 既存の push ステップの直後に追加
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  id: notify
  entrypoint: bash
  args:
    - -c
    - |
      gcloud pubsub topics publish image-updated \
        --message="deploy" \
        --attribute="image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:$SHORT_SHA"
