# cloudbuild/cloudbuild.yaml
substitutions:
  _REGION: asia-northeast1
  _SERVICE: horse-demo
  _AR_REPO: demo-repo
  _IMAGE_NAME: horse
  _APP_DIR: app                 # ← app/ 配下の Dockerfile を使う

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 1) コンテナを app/ でビルド
  - name: gcr.io/cloud-builders/docker
    id: build
    dir: ${_APP_DIR}
    args:
      - build
      - -t
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:$SHORT_SHA'
      - -t
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:latest'
      - .

  # 2) プッシュ（SHA と latest の両方）
  - name: gcr.io/cloud-builders/docker
    id: push-sha
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:$SHORT_SHA']

  - name: gcr.io/cloud-builders/docker
    id: push-latest
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:latest']

  # 3) Cloud Run へデプロイ（イメージだけ差し替え。環境変数/Secretは既存設定を維持）
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: deploy
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy ${_SERVICE} \
          --image='${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:$SHORT_SHA' \
          --region='${_REGION}' \
          --platform=managed \
          --quiet
          --no-wait 

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:$SHORT_SHA'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:latest'
