options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _IMAGE: ""

steps:
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: bash
  args:
    - -c
    - |
        set -euo pipefail
        echo "[deploy] image=${_IMAGE}"
        if [[ -z "${_IMAGE}" ]]; then
          echo "ERROR: _IMAGE is empty" >&2
          exit 1
        fi
        gcloud run deploy horse-demo \
          --image="${_IMAGE}" \
          --region=asia-northeast1 \
          --platform=managed \
          --quiet
