substitutions:
  _REGION: asia-northeast1
  _SERVICE: horse-demo
  _AR_REPO: demo-repo
  _IMAGE_NAME: horse

steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: deploy
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy ${_SERVICE} \
          --image="${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:latest" \
          --region=${_REGION} \
          --platform=managed \
          --quiet
