substitutions:
  _REGION: asia-northeast1
  _SERVICE: horse-demo
  _IMAGE: ""  # Pub/Sub の属性で上書きされる

steps:
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  id: deploy
  entrypoint: bash
  args:
    - -c
    - |
      echo "Deploying ${_SERVICE} with image: ${_IMAGE}"
      gcloud run deploy ${_SERVICE} \
        --image="${_IMAGE}" \
        --region="${_REGION}" \
        --platform=managed \
        --quiet
