# cloudbuild/deploy.yaml
steps:
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: bash
  args:
  - -c
  - |
      set -euo pipefail
      IMG="asia-northeast1-docker.pkg.dev/$PROJECT_ID/demo-repo/horse:latest"
      echo "[deploy] image=${IMG}"
      gcloud run deploy horse-demo \
        --image="${IMG}" \
        --region=asia-northeast1 \
        --platform=managed \
        --quiet
options:
  logging: CLOUD_LOGGING_ONLY
