steps:
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: bash
  args:
    - -c
    - |
        set -euo pipefail
        echo "[deploy] deploying latest image manually..."
        gcloud run deploy horse-demo \
          --image=asia-northeast1-docker.pkg.dev/devops-sre-demo1/demo-repo/horse:latest \
          --region=asia-northeast1 \
          --platform=managed \
          --quiet
